version: "3"
services:
  reservation-postgres:
    image: library/postgres:13
    restart: on-failure
    environment:
      POSTGRES_USER: program
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres
    networks:
      - ds

  reservation:
    build:
      context: ./services
      dockerfile: ../Dockerfile
    entrypoint: /opt/reservation
    restart: on-failure
    networks:
      - ds
    environment:
      - PGHOST=reservation-postgres
      - PGPORT=5432
      - PGUSER=program
      - PGPASSWORD=test
      - PGDB=postgres
      - PGSSL=false
      - PORT=80
    ports:
      - "8070:80"

networks:
  ds:
    driver: bridge